### ISSUE TITLE
Training report error

### ISSUE THREAD

**Issue by FDZ-XL** [WHU-USI3DV/CoFiI2P#15]
Hello, sorry to bother you again. I encountered the following error during training. After checking, it seems to be caused by patc_list being empty. Have you encountered this error before and how can I correct it? I hope you can give me some guidance.

(dlpeizhun) zxl@zxl-Legion-R9000P-ARX8:~/桌面/peizhun/CoFiI2P-main$ python -m train kitti
train set: 40818 frames
load train data complete
val set: 5584 frames
load val data complete
2024-09-18 20:06:43,771 - __main__ - INFO - <data.options.Options_KITTI object at 0x7f89afe5d100>
2024-09-18 20:06:52,445 - __main__ - INFO - train-0-10, loss: 8.878502, loss_desc: 3.459542, loss_coarse: 0.596121, loss_fine: 4.822839
2024-09-18 20:06:58,247 - __main__ - INFO - train-0-20, loss: 9.007816, loss_desc: 3.502417, loss_coarse: 0.678173, loss_fine: 4.827226
2024-09-18 20:07:04,232 - __main__ - INFO - train-0-30, loss: 9.128189, loss_desc: 3.467377, loss_coarse: 0.819809, loss_fine: 4.841004
2024-09-18 20:07:10,057 - __main__ - INFO - train-0-40, loss: 8.907209, loss_desc: 3.447842, loss_coarse: 0.620799, loss_fine: 4.838569
2024-09-18 20:07:15,962 - __main__ - INFO - train-0-50, loss: 8.790735, loss_desc: 3.445036, loss_coarse: 0.526920, loss_fine: 4.818779
2024-09-18 20:07:22,159 - __main__ - INFO - train-0-60, loss: 8.886412, loss_desc: 3.436871, loss_coarse: 0.625806, loss_fine: 4.823734
2024-09-18 20:07:27,962 - __main__ - INFO - train-0-70, loss: 9.152025, loss_desc: 3.467515, loss_coarse: 0.860146, loss_fine: 4.824364
2024-09-18 20:07:34,144 - __main__ - INFO - train-0-80, loss: 8.793801, loss_desc: 3.452446, loss_coarse: 0.524749, loss_fine: 4.816607
2024-09-18 20:07:40,282 - __main__ - INFO - train-0-90, loss: 8.711649, loss_desc: 3.439976, loss_coarse: 0.447469, loss_fine: 4.824203
2024-09-18 20:07:46,364 - __main__ - INFO - train-0-100, loss: 8.819649, loss_desc: 3.444129, loss_coarse: 0.556634, loss_fine: 4.818886
Traceback (most recent call last):
  File "/home/zxl/anaconda3/envs/dlpeizhun/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zxl/anaconda3/envs/dlpeizhun/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zxl/桌面/peizhun/CoFiI2P-main/train.py", line 307, in <module>
    acc = test_acc(model,testloader,opt)
  File "/home/zxl/桌面/peizhun/CoFiI2P-main/train.py", line 70, in test_acc
    , fine_center_xy, coarse_pc_points=model(pc_data_dict,img, fine_center_kpt_coors,fine_xy, fine_pc_inline_index, mode)    # [128, 20, 64] ,[128, 2560]
  File "/home/zxl/anaconda3/envs/dlpeizhun/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zxl/桌面/peizhun/CoFiI2P-main/model/network.py", line 152, in forward
    fine_img_feature_patch = torch.squeeze(extract_patch(img_upsample_s2, fine_center_xy))
  File "/home/zxl/桌面/peizhun/CoFiI2P-main/model/network.py", line 220, in extract_patch
    patch_tensor = torch.stack(patch_list)
RuntimeError: stack expects a non-empty TensorList

**Comment by martin-liao** [comment]
Sorry for not replying in time. I will check the error now.

**Comment by martin-liao** [comment]
We have fixed the validation error [here](https://github.com/WHU-USI3DV/CoFiI2P/blob/main/model/network.py#L137).

**Comment by FDZ-XL** [comment]
Thank you very much. I wish you smooth scientific research and good health.
Additionally, I have a question I would like to ask you and hope you can provide me with an answer.
On line 112 of train.py: parser.add.argument ("-- ft_from", type=str, required=False, help="fine tune from existing checkpoint")
Does this non essential parameter '-- ft_from' refer to the pre training weight you provided (cofi2pukitti. T7)? How was this pre training weight obtained?

**Comment by martin-liao** [comment]
No. 
The ``ft_from`` hyper-parameter is for resuming training after an unexpected interruption.
For the KITTI Odometry and Nuscenes datasets, we trained our models from scratch.

**Comment by FDZ-XL** [comment]
Okay, thank you very much for your answer. Wishing you a happy life!
